### PR TITLE
DeadlockDetector shutup. fixes #145

### LINKED ISSUE #145: OrderedLockTest.testComplex fails on alll platforms since I20220904-1800
OrderedLockTest.testComplex fails on alll platforms since I20220904-1800

Regression from https://github.com/eclipse-platform/eclipse.platform/pull/127

For example in https://download.eclipse.org/eclipse/downloads/drops4/I20220904-1800/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 2 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end

java.lang.AssertionError: testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 2 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end
at org.eclipse.core.tests.runtime.jobs.RetryTestRule$1.evaluate(RetryTestRule.java:50)
```

### PR DESCRIPTION
**Pull request by jukzi**
Logging in DeadlockDetector.reportDeadlock(Deadlock) may timeout test if filesystem is busy.

### CODE REVIEW

**Comment by jukzi** [comment]
`Failed compare-version-with-baselines on project org.eclipse.ant.core`
How is org.eclipse.ant.core related to this change?

**Comment by akurtakov** [comment]
Even if it's not, build will complain about the first comparison failure. Ant.core probably changes due to change in some of the underlying libs.

**Comment by jukzi** [comment]
> Even if it's not, build will complain about the first comparison failure. Ant.core probably changes due to change in some of the underlying libs.

So am i supposed to just increase the version and don't think about it?

**Comment by akurtakov** [comment]
> > Even if it's not, build will complain about the first comparison failure. Ant.core probably changes due to change in some of the underlying libs.
> 
> So am i supposed to just increase the version and don't think about it?

It would be best to understand why this happens but sometimes one has to just bump the version and move on in order to make progress on more important issue.

**Comment by mickaelistria** [comment]
Build issue comes from Tycho. I hope it will be fixed soon enough. Your patience is appreciated.

**Comment by iloveeclipse** [comment]
> Build issue comes from Tycho

COuld you please point to the right ticket? There are many opened.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-tycho/tycho/commit/bcda1a219def8a4082d03284d63366bf9c2fe322

**Comment by iloveeclipse** [comment]
I guess the problem is similar to https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/124

See https://github.com/eclipse-platform/eclipse.platform/pull/184

**Comment by mickaelistria** [comment]
Build issue seems resolved.

**Pull request merged**
