### PR TITLE
Revert "Make LaunchManager's IResourceDeltaVisitors more light weight"

### PR DESCRIPTION
**Pull request by trancexpress**
This reverts commit 8d5bfec6e9f2e6c6136413e0a82062d667029dbc.

Fixes: #1609

### CODE REVIEW

**Comment by merks** [comment]
I was going to suggest that it might be polite to given @HannesWell a chance to comment/review, but that's water under the bridge now...

**Comment by HannesWell** [comment]
> I was going to suggest that it might be polite to given @HannesWell a chance to comment/review, but that's water under the bridge now...

Yes. But I would have appreciated it even more if instead of doing a full revert just the parts that are not trivial would have been reverted. When you are already familiar with the reproducer it will probably relatively easy to filter out the change that caused the regression. Now both of us have to setup a reproducer.

**Comment by iloveeclipse** [comment]
The constraints we had:

- we wanted to fix this regression for RC1
- the original change was not a significant feature that would be worth to wait for RC2 but a refactoring
- pocking around in a code that was seemingly "trivial" but had a subtle bug could cause another regression
- we had no time & recources (I'm offline)
- we had no guarantee Hannes will be there with a fix before RC2

Under these conditions doing a revert was the safest approach.

**Comment by trancexpress** [comment]
> Yes. But I would have appreciated it even more if instead of doing a full revert just the parts that are not trivial would have been reverted. When you are already familiar with the reproducer it will probably relatively easy to filter out the change that caused the regression. Now both of us have to setup a reproducer.

In future, please separate clean-ups from actual changes (with different commits). I would have reverted only the actual changes that cause the bug, if this was the case.

I checked the diff but had no time to divine what actually changed.

**Comment by HannesWell** [comment]
> Under these conditions doing a revert was the safest approach.

Ok, that's understandable, it would just have been nice to have, anyways. Thanks for fixing that issue.
I have now created a second PR with split commits:
- https://github.com/eclipse-platform/eclipse.platform/pull/1618

@trancexpress if you still have the reproducer at hand, it would be nice if you would have a look. If not I'll check if myself.

 

> > Yes. But I would have appreciated it even more if instead of doing a full revert just the parts that are not trivial would have been reverted. When you are already familiar with the reproducer it will probably relatively easy to filter out the change that caused the regression. Now both of us have to setup a reproducer.
> 
> In future, please separate clean-ups from actual changes (with different commits). I would have reverted only the actual changes that cause the bug, if this was the case.

Usually that's what I usually do. I assume in that case I assume that the change is so small and save. But I'm not 100% sure anymore since I did the change four month ago.

**Pull request merged**
