### PR TITLE
Replace org.apache.jasper.glassfish with org.mortbay.jasper.apache-jsp

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1251

### CODE REVIEW

**Comment by merks** [comment]
These could be real failures caused by the JSP changes.  😢 

I'll need to investigate tomorrow...

**Comment by akurtakov** [comment]
Ed, should we merge all the patches you have and start new I-build ? If things work locally for you I think this is the path.

**Comment by merks** [comment]
@akurtakov 

Yes, I think we should merge everything because there might well be chicken-egg problems here and I think it will be easier to fix the ua.tests once all the changes are in...

**Comment by akurtakov** [comment]
Please merge yourself as you know all the needed bits.

**Comment by iloveeclipse** [comment]
@merks : Anything else needed, or can we start I Build to check what's missing?

**Comment by merks** [comment]
I merged the other changes and stated this build:

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.30/14/

**Comment by iloveeclipse** [comment]
`infocenter-product` still has dependency to old library:

```
[2023-09-15T08:24:49.200Z] [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.2:build-qualifier-aggregator (default-build-qualifier-aggregator) on project infocenter-product: Execution default-build-qualifier-aggregator of goal org.eclipse.tycho:tycho-packaging-plugin:4.0.2:build-qualifier-aggregator failed: Could not resolve plugin org.apache.jasper.glassfish_null; Path to dependency:
```

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform/blob/master/ua/infocenter-web/infocenter-product/infocenter.product#L39

@merks : could you please check that product & fix changed dependencies?

**Comment by merks** [comment]
Yes, I'm on that.  Unfortunately that "project" is not in my workspace so is overlooked by searches...

**Pull request merged**
