### PR TITLE
Merge debug

### PR DESCRIPTION
**Pull request by laeubi**
See

- https://github.com/eclipse-platform/eclipse.platform.debug/issues/115

Fix https://github.com/eclipse-platform/eclipse.platform.debug/issues/115

### CODE REVIEW

**Comment by iloveeclipse** [comment]
> This pull request removes 229 tests.

???

**Review by iloveeclipse — DISMISSED** [review]
Git history looks wrong. Looks like all files were **added** in one single commit, not like a merge in platform ui + text where it was an "empty" merge commit of two branches.

**Comment by iloveeclipse** [comment]
> Git history looks wrong. Looks like all files were **added** in one single commit, not like a merge in platform ui + text where it was an "empty" merge commit of two branches.

OK, that was special option "show first parent only" enabled for the debug repo history view. Looks OK.

**Comment by merks** [comment]
FYI, I'm planning ahead for the merge and will want to preserve these working setups, but of course for the merged target location:

image

I'm just recording it here for my own reference later when this is merged.

**Comment by laeubi** [comment]
I have now bumped the versions, so next build should succeed.

**Comment by akurtakov** [comment]
I'll run I-build now. I would like to see successful I-build before this merge goes in.

**Comment by laeubi** [comment]
> I'll run I-build now. I would like to see successful I-build before this merge goes in.

I-Build was successful now: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/36/ :+1:

**Comment by laeubi** [comment]
> > This pull request removes 229 tests.
> 
> ???

This can happen if some tests are executed already and then the build fails (like with version bump required), this is now also fixed and Github shows the new tests added.

**Comment by iloveeclipse** [comment]
Are we ready to merge now? I see the new SDK build is there with mostly clean state: https://download.eclipse.org/eclipse/downloads/drops4/I20230629-0130/testResults.php

**Comment by akurtakov** [comment]
No blockers from my side. I won't be able to work on it in the next couple of hours so everyone is welcome to do whatever they can on the topic and I'll check what's left when back.

**Comment by iloveeclipse** [comment]
@laeubi : will you merge, or who should do that? I would like to have a new build today so we can fix issues before next nightly.

**Comment by akurtakov** [comment]
I'm merging this one now and will proceed with releng.aggregator changes.

**Comment by iloveeclipse** [comment]
As a good tradition, there is a repo.eclipse.org maintenance running in parallel: https://www.eclipsestatus.io/incidents/6372kmdxzlx6

**Pull request merged**
