### PR TITLE
Fix org.apache.jasper.glassfish dependency in infocenter.product

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1251

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse 

Should we just merge this so we can kick off an I-Build?

**Comment by iloveeclipse** [comment]
> @iloveeclipse
> 
> Should we just merge this so we can kick off an I-Build?

Don't we need batch compiler in this product?

**Comment by iloveeclipse** [comment]
In doubt, I would propose to add batch compiler.

**Comment by merks** [comment]
I think it wouldn't hurt and we already realize that we need it (it's package export) in other places so I tend to agree.

Note that we have other "strange dependencies" that I didn't understand their purpose also related to this theme:

https://github.com/eclipse-platform/eclipse.platform/blob/e5f0703cd0427cfda45c9b8c1a02117531b30dfa/ua/org.eclipse.ua.tests/pom.xml#L58-L69

**Comment by merks** [comment]
@iloveeclipse 

FYI, it looks like the continuous-integration/jenkins/pr-head build got past building the infocenter-product:
```
09:03:56.831 [INFO] --- tycho-apitools:4.0.2:verify (verify) @ infocenter-product ---
09:03:56.833 [INFO] 
09:03:56.833 [INFO] ---------< eclipse.platform.ua:org.eclipse.ui.intro.universal >---------
```
Do you still think it's best to include the batch compiler immediately?

**Comment by merks** [comment]
Everything appears to have build, but there continue to be test failures that may well be because of missing things but those things might handled previous via the pom dependencies as mentioned here:

https://github.com/eclipse-platform/eclipse.platform/pull/688#issuecomment-1720934878

@iloveeclipse 

Please advise at how you would like to proceed...  I think/hope that with these changes the I-Build would work, although with test failures...

**Comment by iloveeclipse** [comment]
Compile time doesn't need "jsp compiler" but at runtime product will miss the compiler package for sure.
Ed, please add batch compiler to the product, merge PR & start I Build.

**Comment by iloveeclipse** [comment]
> Note that we have other "strange dependencies" that I didn't understand their purpose also related to this theme:

No idea. I guess an attempt to make similar change like we do now.

**Comment by merks** [comment]
Build running:

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.30/15/

**Comment by merks** [comment]
@iloveeclipse 

The build completed.

I assume there are likely to be test failures, though those UA tests are passing for me...

image

**Pull request merged**
