### PR TITLE
team.SWTUtils - fix missing break in switch

### PR DESCRIPTION
**Pull request by JAndrassy**
I maintain the CVS plugin and this error makes it crash in 2024-03.
the Issue: https://github.com/JAndrassy/org.eclipse.team.cvs/issues/5

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Please bump org.eclipse.team.ui version (third segment) by +100
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.7-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.team.ui: Only qualifier changed for (org.eclipse.team.ui/3.10.300.v20240318-1452). Expected to have bigger x.y.z than what is available in baseline (3.10.300.v20240207-1044) 
```

**Comment by JAndrassy** [comment]
> Please bump org.eclipse.team.ui version (third segment) by +100

sorry, I have no clue about Eclipse platform development.
3.10.300 to 3.10.400?
in which file? MANIFEST.MF or .polyglot.META-INF or both? in tests too?

**Comment by iloveeclipse** [comment]
> in which file? MANIFEST.MF or .polyglot.META-INF or both? in tests too?

Here only: https://github.com/eclipse-platform/eclipse.platform/blob/c74c80065aa91f5e2f03377aae1cd80928e48534/team/bundles/org.eclipse.team.ui/META-INF/MANIFEST.MF#L5

> 3.10.300 to 3.10.400?

Yes

**Comment by iloveeclipse** [comment]
Could you please talk with each other and decide which PR should be merged? 
See https://github.com/eclipse-platform/eclipse.platform/pull/1254

**Pull request closed without merging**
