### PR TITLE
Fix silently failing IResourceChangeListenerTest.testRefreshOtherProjectDuringRefresh() #364

### LINKED ISSUE #364: AssertionFailedError logged during IResourceChangeListenerTest.testRefreshOtherProjectDuringRefresh()
Exception is not thrown in the testing thread so the Test does not fail, but reproducible logs

https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/ep426I-unit-win32-java11_win32.win32.x86_64_11/org.eclipse.core.tests.resources.AutomatedTests.txt
```
junit.framework.AssertionFailedError: 4.0
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:223)
	at org.eclipse.core.tests.resources.IResourceChangeListenerTest$1Listener2.resourceChanged(IResourceChangeListenerTest.java:893)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:279)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:383)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1572)
	at org.eclipse.core.tests.resources.IResourceChangeListenerTest$3Listener1$1.run(IResourceChangeListenerTest.java:871)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

### PR DESCRIPTION
**Pull request by HeikoKlare**
The test case `IResourceChangeListenerTest.testRefreshOtherProjectDuringRefresh()` was silently failing as stated in #364. Assertions thrown within listeners processed by others than the main thread are not treated as failures by JUnit. Thus, in case of regressions several test cases in the `IResourceChangeListenerTest` would not properly fail. This PR proposes a solution that does the following:
* Fixes misplaced assertion in `testRefreshOtherProjectDuringRefresh` leading to the (silent) test failure
* Moves all assertions into main thread, so in case they fail they will properly lead to test failures

Since I am unsure whether it is necessary to have the numbered assertion failures messages (`1.0`, `2.0` etc.), I sticked to the existing messages in most cases.

Fixes #364.

### CODE REVIEW

**Comment by HeikoKlare** [comment]
The failing test also occurs in unrelated pull requests. I have opened an issue for that: https://github.com/eclipse-platform/eclipse.platform/issues/373

**Comment by vogella** [comment]
@jukzi is the unit test error on Mac already known? https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-366/7/testReport/junit/org.eclipse.core.tests.internal.localstore/FileSystemResourceManagerTest/testWriteFile/

**Comment by jukzi** [comment]
looks like that is random failing:
https://github.com/search?q=FileSystemResourceManagerTest.testWriteFile&type=issues
https://github.com/eclipse-platform/eclipse.platform/issues/103

**Comment by vogella** [comment]
@jukzi please merge if you are fine with the changes, at the moment I lost a bit the overview which builds are failing on which platform in which repo after we now run all verification builds on all platforms (which is a good change from to make the tests more stable)

**Comment by jukzi** [comment]
Sorry out of time: With all those failing tests i feel lost to interpret which errors are related. For me the new build system feels broken.

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
> Since I am unsure whether it is necessary to have the numbered assertion failures messages (1.0, 2.0 etc.), I sticked to the existing messages in most cases.

No, it is not, it is just our "legacy" which we have. If you see such code, feel free to replace it with proper assertion messages.

The change makes sense, but as before, I would prefer you would amend the commit and provide a commit message that explains the change.

**Comment by HeikoKlare** [comment]
Perfect. Next time I come around such code, I will also improve the assertion messages.

I have amended the commit with an explanation of the change.

**Review by iloveeclipse — APPROVED** [review]

**Pull request merged**
