### PR TITLE
Replace deprecated core.launcher.Main by equinox.launcher.Main

### PR DESCRIPTION
**Pull request by HannesWell**
Required for https://github.com/eclipse-equinox/equinox/pull/562

### CODE REVIEW

**Comment by HannesWell** [comment]
The test-failures seem to be the same as on the master, but I assume they are caused by https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1919#issuecomment-2017845314, aren't they?
I'll await tonight's I-build and hope the build is then green again.

**Comment by akurtakov** [comment]
In https://github.com/eclipse-platform/eclipse.platform/actions/runs/8426539577/job/23092286324?pr=1266 I can see it's some test failure in ant.tests.ui but can't figure more from the log. Can someone help finding the details?

**Comment by akurtakov** [comment]
As Jenkins succeeds it's fine to merge.

**Comment by HannesWell** [comment]
> > The test-failures seem to be the same as on the master, but I assume they are caused by [eclipse-platform/eclipse.platform.releng.aggregator#1919 (comment)](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1919#issuecomment-2017845314), aren't they?
> > I'll await tonight's I-build and hope the build is then green again.
> 
> Probably, yes. The same failures occur in other PRs, such as #852. I've retriggered the GH actions for #852 this morning, when yesterday's I-Build had been deployed, but the same failures still occur.

Thanks Heiko.
It might still happen since I-builds are unstable since https://download.eclipse.org/eclipse/downloads/drops4/I20240324-1800/.
But I don't have time to investigate before this evening, although just fixing it would be simple since just one bundle is affected.




> As Jenkins succeeds it's fine to merge.

Me too and since the deprecated class just wraps the replacement in the same bundle I think it is relatively save. When I used it locally in my IDE it worked.

**Comment by HeikoKlare** [comment]
> In https://github.com/eclipse-platform/eclipse.platform/actions/runs/8426539577/job/23092286324?pr=1266 I can see it's some test failure in ant.tests.ui but can't figure more from the log. Can someone help finding the details?

I did not have time to investigate yet, but I could imagine that this is somehow related to using a Java 21 JVM. I also face and currently investigate issues in another PR, in which a test is working fine when run with a Java 17 JVM but does not succeed with a Java 21 one: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1775

**Comment by HeikoKlare** [comment]
I just verified: Running the Ant UI tests with a Java 21 JVM locally produces the same test failures as the GH actions builds here.

**Comment by merks** [comment]
I wonder if `-Djava.security.manager=allow` makes a different to the test behavior?

**Comment by akurtakov** [comment]
https://ci.eclipse.org/platform/job/eclipse.platform/job/master/768/ is finally a good build with even comparator issues fixed.

**Comment by HeikoKlare** [comment]
> I wonder if `-Djava.security.manager=allow` makes a different to the test behavior?

Yes, that makes the Ant UI tests run properly.

**Pull request merged**
