### PR TITLE
Build o.e.core.tools.resources and fix compile-error

### PR DESCRIPTION
**Pull request by HannesWell**
Fixes https://github.com/eclipse-platform/eclipse.platform/issues/82

### CODE REVIEW

**Comment by akurtakov** [comment]
The build fails on warnings so if you want to enable this module you have to fix the warnings or disable them.

**Comment by HannesWell** [comment]
> The build fails on warnings so if you want to enable this module you have to fix the warnings or disable them.

Hope this is done now.

Other question: Is the merge of platform.resources into this repository completed so that I can merge this PR if the build is green? There was no announcement yet and some things have to be adjusted, mainly the Oomph setup, but I can do that.

**Comment by akurtakov** [comment]
Please merge when done. @iloveeclipse fixed the merge late yesterday and I guess @laeubi will send the announcement soon.

**Comment by HannesWell** [comment]
> Please merge when done. @iloveeclipse fixed the merge late yesterday and I guess @laeubi will send the announcement soon.

Alright. Thanks. I read Andreys announcement. And I have to correct myself regarding the Oomph setup. Ed already did that in the aggregator.

**Comment by merks** [comment]
I've been specifically filtering this project out of the setup.

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/c0e43da419549262069b16deaa9a76558cd12e16/oomph/Platform.setup#L201-L213

But when this is merged, I can remove that...  Cool.

**Comment by HannesWell** [comment]
> I've been specifically filtering this project out of the setup.
> 
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/c0e43da419549262069b16deaa9a76558cd12e16/oomph/Platform.setup#L201-L213
> 
> But when this is merged, I can remove that... Cool.

I know. :D Have already prepared a change for that.
I'm just waiting for this change to complete.

**Comment by HannesWell** [comment]
The build succeeds without new warnings (the only failure is probably unrelated) and the two projects are now build as intended:
- `org.eclipse.core.tools.resources`
- `org.eclipse.core.resources.spysupport`

-> Ready for merge.

**Pull request merged**
