### PR TITLE
Remove 2018 deprecated runtime contenttype extension point

### PR DESCRIPTION
**Pull request by vogella**
In 2018 we marked this extension point for deletion, lets remove it for 2025-03.

### CODE REVIEW

**Comment by vogella** [comment]
@HannesWell I do not see the version increase commit from [eclipse-platform-bot](https://github.com/eclipse-platform-bot) in this PR. Did I do something wrong? I will now rebase and see if the bot can add the version increase commit now.

**Comment by HannesWell** [comment]
> In 2018 we marked this extension point for deletion, lets remove it for 2025-03.

Have you checked if the extension-point is used anywhere in the SDK? I remember that quite a number of extensions for deprecated points exit.


> @HannesWell I do not see the version increase commit from eclipse-platform-bot in this PR. Did I do something wrong? I will now rebase and see if the bot can add the version increase commit now.


The log of the publication workflow says that the bot is not permitted to push to your repository.
Have you disabled edits by maintainers?

**Comment by vogella** [comment]
> Have you disabled edits by maintainers?

No, but I learned from https://github.com/orgs/community/discussions/5634 that:  if a PR is created from a fork living under an organisation (rather than an individual) it's not possible to allow edits by maintainers

So instead of sending PR from @vogellacompany I'm supposed to send them from @vogella to get this working. Thanks for the answer @HannesWell

**Comment by vogella** [comment]
New PR https://github.com/eclipse-platform/eclipse.platform/pull/1644

**Pull request closed without merging**
