### PR TITLE
Update ForceQualifier for Comparator errors in I20240904-1800

### PR DESCRIPTION
**Pull request by MohananRahul**

### CODE REVIEW

**Comment by akurtakov** [comment]
This doesn't seem to be enough based on yesterdays force qualifier update.

**Comment by MohananRahul** [comment]
> This doesn't seem to be enough based on yesterdays force qualifier update.

Baseline change to RC2a after yesterday forcequailfier update may be cause new comparator error.

**Comment by iloveeclipse** [comment]
I've triggered new build https://ci.eclipse.org/releng/job/Builds/job/I-build-4.34/6/ to get stable state

**Comment by akurtakov** [comment]
> > This doesn't seem to be enough based on yesterdays force qualifier update.
> 
> Baseline change to RC2a after yesterday forcequailfier update may be cause new comparator error.

Looks like this was not the case as https://download.eclipse.org/eclipse/downloads/drops4/I20240905-1800/ failed again with same comparator issue.

**Comment by MohananRahul** [comment]
> > > This doesn't seem to be enough based on yesterdays force qualifier update.
> > 
> > 
> > Baseline change to RC2a after yesterday forcequailfier update may be cause new comparator error.
> 
> Looks like this was not the case as https://download.eclipse.org/eclipse/downloads/drops4/I20240905-1800/ failed again with same comparator issue.

Yes, but still https://ci.eclipse.org/releng/job/Builds/job/I-build-4.34/6/ got stable build.

**Comment by akurtakov** [comment]
> > > > This doesn't seem to be enough based on yesterdays force qualifier update.
> > > 
> > > 
> > > Baseline change to RC2a after yesterday forcequailfier update may be cause new comparator error.
> > 
> > 
> > Looks like this was not the case as https://download.eclipse.org/eclipse/downloads/drops4/I20240905-1800/ failed again with same comparator issue.
> 
> Yes, but still https://ci.eclipse.org/releng/job/Builds/job/I-build-4.34/6/ got stable build.

That's because it was "forced" to override qualifier. Doing that for every build is not a working solution.

**Pull request merged**
