### PR TITLE
Fix Cut Off Label on Welcome Page

### PR DESCRIPTION
**Pull request by BeckerWdf**
This is the second attempt as the initial fix needed to be reverted.

Fixes: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1210

### CODE REVIEW

**Comment by BeckerWdf** [comment]
I don't understand the results of the build.
What's wrong here?
Am I doing something wrong?

**Comment by iloveeclipse** [comment]
> I don't understand the results of the build.

Me either, welcome in the club.

> What's wrong here?

No idea.

> Am I doing something wrong?

No, it looks like "quality gate" that seem to thread maven warnings as test failures. Or it is the "quality gate" that don't understands javadoc errors, see #1017. Or it is something else...

In overall, usually people fail to understand what exactly "quality gate" is supposed to say and usually it turns out to be just noise so everyone learns to ignore all the errors reported, which is exact the opposite of what we want.

There was an attempt to mute it for maven in https://github.com/eclipse-platform/eclipse.platform/pull/1007 (after long discussion on #969), but it seem not work reliably, or it is something else that is now need to be muted.

@jukzi : if you know what current build is complaining about, it would be nice if you could mute that too.

**Comment by jukzi** [comment]
complains about ecj warnings, probably because warning have been just enabled https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/cf74f8dd21c95885cd9e4c96837b814f99e5434b
image
That is supposed to settle for in the future.

**Comment by jukzi** [comment]
ignore that ecj quality gate today

**Comment by BeckerWdf** [comment]
> ignore that ecj quality gate today

So should I merge this change?

**Pull request merged**
