### PR TITLE
Remove thresholds for (static) imports from many project settings #442

### PR DESCRIPTION
**Pull request by fedejeanne**
Several projects override these 2 properties in **.settings/org.eclipse.jdt.ui.prefs**:
* `org.eclipse.jdt.ui.ondemandthreshold`
* `org.eclipse.jdt.ui.staticondemandthreshold`
 
The problem is that some set values that do **not** follow the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions), specifically this one:

> Use "organize imports" (Ctrl-Shift-O) to clean up the imports (we do **not** use org.eclipse.* type notation).

My fix simply removes the overrides of these 2 settings in several projects, which means the projects will use the default value of **99** (which honors the coding conventions).

Issue #442

### CODE REVIEW

**Comment by Bananeweizen** [comment]
I can't judge how well maintained the coding conventions page is, but I'm all for completely avoiding star imports except for well known favorite imports (like assertion libraries), and those are configured independently of this setting.

**Review by Bananeweizen — APPROVED** [review]

**Comment by HeikoKlare** [comment]
I agree that star imports should be avoided (which also conforms to the coding conventions).
Maybe instead of removing the defined thresholds we could set them all to 99, such that no matter how someone has configured his or her workspace, star imports will be avoided? Seems like "newer" projects such as the e4 ones have already set these values to 99 accordingly.

**Comment by Bananeweizen** [comment]
>  we could set them all to 99

I prefer that way strongly in my own projects (where _every_ preference is defined in _every_ project via some scripting), simply to have reproducable builds over time, machines, and people. However, in most open source projects I see many people reacting rather awkward on "repeating default settings everywhere" (might it be eclipse preferences, maven pom properties or whatever). So be warned, there might be some debate. :)

**Comment by HeikoKlare** [comment]
Thanks for the warning 🙂 I don't want to start a debate on that and if someone has a strong opinion on that topic, I will gladly accept that.
I'd also prefer to have some better centralized/maintainble approach to achieve consistent code style rather than repeating default settings, but having these settings in every projects seem to be the most lightweight approach to achieve that.
If you have a workspace with projects expecting different code style defaults. it becomes difficult without having them set in the according projects.

**Review by HeikoKlare — CHANGES_REQUESTED** [review]
Can you please also adapt settings in these projects to be consistent across all existing projects:
* org.eclipse.core.contenttype
* org.eclipse.core.contenttype.tests
* org.eclipse.core.expressions.tests
* org.eclipse.team.ui

**Comment by fedejeanne** [comment]
@HeikoKlare done

**Review by HeikoKlare — APPROVED** [review]
Thanks!

**Comment by akurtakov** [comment]
I would appreciate if you rebase on top of master before merging in order to catch up needed version bumps. After this patch we have https://download.eclipse.org/eclipse/downloads/drops4/I20230616-1800/buildlogs/reporeports/reports/versionChecks.html :

<h2>IUs in current repo that increase versions but with qualifier only</h2>
<p>Count: 40


IU id | Reference (old) version | Current (new) version
-- | -- | --
org.eclipse.ant.core | 3.7.0.v20230329-1001 | 3.7.0.v20230616-1042
org.eclipse.ant.core.source | 3.7.0.v20230329-1001 | 3.7.0.v20230616-1042
org.eclipse.ant.tests.core | 3.7.0.v20230329-1001 | 3.7.0.v20230616-1042
org.eclipse.ant.tests.core.source | 3.7.0.v20230329-1001 | 3.7.0.v20230616-1042
org.eclipse.ant.tests.ui | 3.11.0.v20230417-0913 | 3.11.0.v20230616-1042
org.eclipse.ant.tests.ui.source | 3.11.0.v20230417-0913 | 3.11.0.v20230616-1042
org.eclipse.compare.examples | 3.4.0.v20230317-0901 | 3.4.0.v20230616-1042
org.eclipse.compare.examples.source | 3.4.0.v20230317-0901 | 3.4.0.v20230616-1042
org.eclipse.compare.win32 | 1.3.0.v20230317-0901 | 1.3.0.v20230616-1042
org.eclipse.compare.win32.source | 1.3.0.v20230317-0901 | 1.3.0.v20230616-1042
org.eclipse.core.contenttype | 3.9.0.v20230412-0829 | 3.9.0.v20230616-1042
org.eclipse.core.contenttype.source | 3.9.0.v20230412-0829 | 3.9.0.v20230616-1042
org.eclipse.core.expressions.tests | 3.7.0.v20230317-0901 | 3.7.0.v20230616-1042
org.eclipse.core.expressions.tests.source | 3.7.0.v20230317-0901 | 3.7.0.v20230616-1042
org.eclipse.core.filesystem | 1.10.0.v20230425-0513 | 1.10.0.v20230616-1042
org.eclipse.core.filesystem.source | 1.10.0.v20230425-0513 | 1.10.0.v20230616-1042
org.eclipse.core.net | 1.5.0.v20230317-0901 | 1.5.0.v20230616-1042
org.eclipse.core.net.source | 1.5.0.v20230317-0901 | 1.5.0.v20230616-1042
org.eclipse.core.net.win32 | 1.1.0.v20230317-0901 | 1.1.0.v20230616-1042
org.eclipse.core.net.win32.source | 1.1.0.v20230317-0901 | 1.1.0.v20230616-1042
org.eclipse.core.net.win32.x86_64 | 1.2.0.v20230317-0901 | 1.2.0.v20230616-1042
org.eclipse.core.net.win32.x86_64.source | 1.2.0.v20230317-0901 | 1.2.0.v20230616-1042
org.eclipse.core.tests.net | 1.6.0.v20230317-0901 | 1.6.0.v20230616-1042
org.eclipse.core.tests.net.source | 1.6.0.v20230317-0901 | 1.6.0.v20230616-1042
org.eclipse.core.tests.runtime | 3.21.0.v20230515-1832 | 3.21.0.v20230616-1042
org.eclipse.core.tests.runtime.source | 3.21.0.v20230515-1832 | 3.21.0.v20230616-1042
org.eclipse.e4.core.di.annotations | 1.8.0.v20230429-1914 | 1.8.0.v20230616-1042
org.eclipse.e4.core.di.annotations.source | 1.8.0.v20230429-1914 | 1.8.0.v20230616-1042
org.eclipse.e4.core.tests | 1.3.0.v20230429-1807 | 1.3.0.v20230616-1042
org.eclipse.e4.core.tests.source | 1.3.0.v20230429-1807 | 1.3.0.v20230616-1042
org.eclipse.jsch.tests | 1.6.0.v20230317-0901 | 1.6.0.v20230616-1042
org.eclipse.jsch.tests.source | 1.6.0.v20230317-0901 | 1.6.0.v20230616-1042
org.eclipse.team.genericeditor.diff.extension | 1.2.0.v20230317-0901 | 1.2.0.v20230616-1042
org.eclipse.team.genericeditor.diff.extension.source | 1.2.0.v20230317-0901 | 1.2.0.v20230616-1042
org.eclipse.team.tests.core | 3.10.0.v20230417-1006 | 3.10.0.v20230616-1042
org.eclipse.team.tests.core.source | 3.10.0.v20230417-1006 | 3.10.0.v20230616-1042
org.eclipse.ui.examples.filesystem | 1.1.0.v20230317-0901 | 1.1.0.v20230616-1042
org.eclipse.ui.examples.filesystem.source | 1.1.0.v20230317-0901 | 1.1.0.v20230616-1042
org.eclipse.ui.net | 1.5.0.v20230317-0901 | 1.5.0.v20230616-1042
org.eclipse.ui.net.source | 1.5.0.v20230317-0901 | 1.5.0.v20230616-1042

</p>

**Comment by akurtakov** [comment]
I'll handle it now but please keep an eye for this things for the future as needed version bumps prevent any other patch verification build to succeed until fixed.

**Comment by HeikoKlare** [comment]
@akurtakov I am very sorry for that. I usually rebase before merging but I mistakely thought that these changes are free of any side effects due to only affecting the configuration for dev/compile time. But since those configuration files can, in general, have effects on the deployed artifacts, it makes sense that versions need to be bumped. Thanks for correcting my mistake! Won't happen again.

**Pull request merged**
