### PR TITLE
Disable InjectionOSGiTest if needed #1098

### PR DESCRIPTION
**Pull request by jukzi**
Convert assert to assume to disable false-positive in I-Builds. https://github.com/eclipse-platform/eclipse.platform/issues/1098

### CODE REVIEW

**Comment by jukzi** [comment]
That test is failing for 5 months now and i have seen no progress, tired to see it in every i build.

**Comment by iloveeclipse** [comment]
> That test is failing for 5 months now and i have seen no progress, tired to see it in every i build.

Fully agree. 

However: as long as no real fix is in sight, instead of using "assume": could we add environment variable in Jenkinsfile & do not fail the test on official builds where this variable is not specified? 
This way we still can have the test failing in Jenkins in case same problem with the target platform will appear there.

**Comment by HeikoKlare** [comment]
I totally agree that the persisting test failure is very annoying, but still I want to state that in my opinion this kind of temporary fix is _wrong_ (see the discussion in #1098). With this change, we will not notice when for whatever reasons also the GH Actions builds do not execute the tests properly anymore and thus we may end up in having no validation for the javax annotations without taking notice.

> However: as long as no real fix is in sight, instead of using "assume": could we add environment variable in Jenkinsfile & do not fail the test on official builds where this variable is not specified?

Couldn't we also do something like removing the test plug-in from the Ant specifications used by the Jenkins build? The test plug-in is currently useless in the Jenkins builds anyway (as it tests the same as the "ordinary" test plug-ins using the jakarta annotation).

**Comment by jukzi** [comment]
If anyone is really interested in that test why shouldn't he use his time to fix it - instead of insisting it should not be disabled? 
5 month it is failing and no one cared. Who would care if it really fails instead of false-positive?

**Comment by jukzi** [comment]
> This pull request removes 1 test.
> ```
> CoreTestSuite org.eclipse.e4.core.internal.tests.di.extensions.InjectionOSGiTest ‑ ensureJavaxIsNotAvailable
> ```

this is intended, 
the failing ParallelBuildChainTest is unrelated,
macos: `Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.8-SNAPSHOT:verify (verify) on project org.eclipse.help.webapp: Execute ApiApplication failed: InvocationTargetException: Component 'Help System Webapp' in the baseline 'workspace' is disposed: Component was disposed here -> [Help 1]` is unrelated.

InjectionOSGiTest is still executed and green on jenkins CI:
image
https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1364/2/testReport/CoreTestSuite%20org.eclipse.e4.core.internal.tests.di.extensions/InjectionOSGiTest/

If anybody wants another solution please work on it timely.

**Comment by HeikoKlare** [comment]
> If anyone is really interested in that test why shouldn't he use his time to fix it - instead of insisting it should not be disabled?
> 5 month it is failing and no one cared. Who would care if it really fails instead of false-positive?

1. We are (or should) all be intestered in that test as it is part of the validation for the product we are all together responsible for. Do you think there is someone particularly reponsible for this test and its failure?
2. I think there is some misunderstanding regarding the meaning of this single test case: It is not about a single test but about the complete test plug-in. This single test case identifies whether all the other tests in that same plug-in make any sense at all (as it checks for the proper configuration in which the plug-in is run).
3. The test runs fine in GH actions builds.
4. Because of (3), no one says the test should not be disabled, but it should be disabled _selectively_ only where it is not configured properly (for whatever reasons).

**Comment by jukzi** [comment]
> Do you think there is someone particularly reponsible for this test and its failure?

sure - if someone contributes a test he should keep it alife. in this case @HannesWell contributed it. Anyway as we can not force anybody to work on anything the typical way is to just disable false positives, as say do not add any value but disturb.

> The test runs fine in GH actions builds.

this PR does not change that.

> 4\. Because of (3), no one says the test should not be disabled, but it should be disabled _selectively_ only where it is not configured properly (for whatever reasons).

Then please do it.

**Comment by HeikoKlare** [comment]
> sure - if someone contributes a test he should keep it alife

I completely disagree here. That would be a great incentive to _not_ provide tests. I have fixed so many tests that I did not contribute, no matter whether the initial contributor was still active or not. There have been several tests badly written, containing race conditions, missing isolatation etc., but I would have never thought about blaming anyone for contributing the test and not fixing it when it started to fail. In particular in this case, the problem is not even about the test itself but about the execution environment.

> > The test runs fine in GH actions builds.
> 
> this PR does not change that.

Depends on what you define as "running fine". I have explained the effects of this PR on the GH actions builds before: if those builds start to pull in unexpected annotations as well, no will notice after this PR as they will simply not be executed anymore.

**Review by HannesWell — CHANGES_REQUESTED** [review]
I fully agree with Heiko here, so I won't repeat that. But just because there has not been a solution it doesn't mean there is progress or at least work happening. I simply didn't have the time to complete the work since the I build environment is not trivial to understand and I had a lot of other things to do.

But I can probably push a PR that selectively disables the configuration test case in I-builds as suggested by Heiko.

**Comment by jukzi** [comment]
> But I can probably push a PR that selectively disables the configuration test case in I-builds as suggested by Heiko.

would be very welcome

**Comment by HannesWell** [comment]
> > But I can probably push a PR that selectively disables the configuration test case in I-builds as suggested by Heiko.
> 
> would be very welcome

Please see https://github.com/eclipse-platform/eclipse.platform/pull/1365.

**Pull request closed without merging**
