### PR TITLE
Merge team repo

### PR DESCRIPTION
**Pull request by laeubi**
See https://github.com/eclipse-platform/.github/issues/12

### CODE REVIEW

**Comment by laeubi** [comment]
This most likely will require to disable the branch protection for a while...

**Review by vogella — APPROVED** [review]
Looks good to merge. Merge commits are now allowed so feel free to merge this one.

I won't be around the rest of the day, so in case you want my support for the remaining tasks like updating the aggregator build and potential updates in the Javadoc generation, you should merge early tomorrow morning.

Or get support from @vik-chand or @akurtakov

**Comment by laeubi** [comment]
Thanks, change is merged, so merge-commit can be disabled again.

**Comment by vogella** [comment]
Allow merge commits disabled.

**Comment by vogella** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/434 and https://github.com/eclipse-platform/eclipse.platform.common/pull/58

**Pull request merged**
