### PR TITLE
Suppress deprecation: java.util.Observable

### PR DESCRIPTION
**Pull request by jukzi**
There is no plan to change the implementation

### CODE REVIEW

**Comment by jukzi** [comment]
jenkins plugin shows warnings that are not shown in workspace:
image
may be related to `<code.ignoredWarnings>-warn:-deprecation,raw,unchecked</code.ignoredWarnings>` in pom.xml?

**Comment by jukzi** [comment]
@akurtakov should "code.ignoredWarnings" in all projects be removed or replaced by
"<code.ignoredWarnings>${tests.ignoredWarnings}</code.ignoredWarnings>" in order to get the same result as in workspace?

**Comment by laeubi** [comment]
Last time I though we wanted to simply use project settings, so maybe just remove that at all?

**Comment by akurtakov** [comment]
I agree that it would be best if workspace and maven build warnings are the same.

**Comment by jukzi** [comment]
the ecj jenkins plugin still (or again?) validiates against the wrong base:
```
[ReferenceFinder] Found reference build '#697' for target branch
[Eclipse ECJ] Obtaining reference build from reference recorder
[Eclipse ECJ] -> Found 'eclipse.platform » master #697'
[Eclipse ECJ] Using reference build 'eclipse.platform/master #696' to compute new, fixed, and outstanding issues
[Eclipse ECJ] Issues delta (vs. reference build): outstanding: 62, new: 0, fixed: 9
```
image

probably because 697 failed a test.
wonder why 698 is not use.

**Pull request merged**
