### PR TITLE
Migrate all tests in o.e.c.tests.internal.mapping to JUnit 4 #903

### PR DESCRIPTION
**Pull request by HeikoKlare**
* Replace the ResourceTest class hierarchy with WorkspaceTestRule
* Add `@Test` annotations

Contributes to https://github.com/eclipse-platform/eclipse.platform/issues/903

### CODE REVIEW

**Comment by HeikoKlare** [comment]
Ignoring unrelated Maven and ECJ warnings in Jenkins build.

**Comment by akurtakov** [comment]
The pattern of ignoring warnings starts to bother me (once people get used to ignoring things become bad fast) - we should have smth bad in our config if unrelated warnings pop ups. 
@HeikoKlare Have you looked at the underlying issues?

**Comment by HeikoKlare** [comment]
@akurtakov I totally agree with you. My wording was just too sloppy: I do never really _ignore_ warnings but just did not consider them for this  (and other) PRs, as they are really unrelated _and_ already tracked in other issues/PR:
1. https://github.com/eclipse-platform/eclipse.platform/issues/969
Tracks the Maven warnings, which will be resolved in Equinox: https://github.com/eclipse-equinox/equinox/pull/403
2. https://github.com/eclipse-platform/eclipse.platform/pull/972
Tracks the changes necessary to resolve the ECJ warnings, which are a result of deprecations in Equinox: https://github.com/eclipse-equinox/equinox/pull/403

**Comment by akurtakov** [comment]
@laeubi https://github.com/eclipse-tycho/tycho/commit/697dc929fd0800c913225f6fcc560dd8c3c6ab40 should stabilize/improve things at least with less warnings, right?

**Pull request merged**
