### PR TITLE
Improve Compare result for structured text #66

### PR DESCRIPTION
**Pull request by jukzi**
Prefer many common tail lines over many common head lines.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please share 1 example?

**Comment by jukzi** [comment]
> Can you please share 1 example?

see https://github.com/eclipse-platform/eclipse.platform/issues/66#issue-1326910306

**Comment by mickaelistria** [comment]
Thanks!

**Comment by jukzi** [comment]
unrelated random fails:
https://github.com/eclipse-platform/eclipse.platform/issues/320 
https://github.com/eclipse-platform/eclipse.platform/issues/319

**Comment by jukzi** [comment]
won't fix

**Pull request closed without merging**
