### PR TITLE
Add windowsPR GH action verification

### PR DESCRIPTION
**Pull request by akurtakov**
Pre-req to investigate
https://github.com/eclipse-platform/eclipse.platform/issues/265

### CODE REVIEW

**Comment by laeubi** [comment]
@akurtakov you better can use a matrix build here, see for example the Tycho workflow.

**Comment by laeubi** [comment]
We might even add mac as well ...

**Comment by akurtakov** [comment]
Do you want to enhanche this PR ? My GH action-foo is still not good enough but I try ;) .

**Comment by akurtakov** [comment]
Right now I would probably keep the matrix to the minimum and extend when needed to not delay win investigation with possible mac issues.

**Comment by laeubi** [comment]
I'll propose a patch!

**Comment by akurtakov** [comment]
> I'll propose a patch!

Thanks a lot!

**Comment by akurtakov** [comment]
Close in favor of https://github.com/eclipse-platform/eclipse.platform/pull/273 as @laeubi teaches me :)

**Pull request closed without merging**
