### PR TITLE
 Merging eclipse.platform.runtime into eclipse.platform 

### PR DESCRIPTION
**Pull request by vogella**
Merging eclipse.platform.runtime into eclipse.platform repo

As decided by the PMC the runtime repo is merged into the
eclipse.platform to reduce releng effort and to make commmunity
contributions easier.

Conflicts:
	.gitignore
	Jenkinsfile
	pom.xml

Manual adjustment of the pom files from runtime to update the parent ID.

### CODE REVIEW

**Comment by vogella** [comment]
As we only moved commits from runtime to this repo the eca check is covered by the runtime repo commits, so the eca failing check it not relevant here.

**Comment by mickaelistria** [comment]
Note that I'm not asking for a change here, but more bringing food for thought for future merge: wouldn't have it been simpler to create a root `runtime` folder in the repo? In the future, this would prevent from conflicts when merging other parts; and also I think it keeps "architecture" more explicit and easier to understand for newcomers and even old-timers.

**Comment by vogella** [comment]
> Note that I'm not asking for a change here, but more bringing food for thought for future merge: wouldn't have it been simpler to create a root `runtime` folder in the repo? In the future, this would prevent from conflicts when merging other parts; and also I think it keeps "architecture" more explicit and easier to understand for newcomers and even old-timers.

Done, runtime content is now in a "runtime" folder.

**Review by akurtakov — APPROVED** [review]

**Comment by laeubi** [comment]
Just for the record I see build times of around 10 minutes on "old" master and 13min for this PR, so it seems quite good.

Next could be to add GH action here and play with parallel execution.

**Comment by mickaelistria** [comment]
> Just for the record I see build times of around 10 minutes on "old" master and 13min for this PR, so it seems quite good.

Yes, very good!

**Pull request merged**
