### PR TITLE
send cookies via secure channel

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-platform/eclipse.platform/security/code-scanning/24

### CODE REVIEW

**Comment by jukzi** [comment]
> Please verify that the help system still works with this change. The code and ideas there are pretty ancient so bigger changes might be needed (hopefully not) .

The code is called in for example org.eclipse.ua.tests.help.search.InfocenterWorkingSetManagerTest.testIWSMWithTwoTopics() and the test does not fail. Does anybody have other ideas how to test? I don't even know where it is used in real live.

**Comment by iloveeclipse** [comment]
> Does anybody have other ideas how to test? I don't even know where it is used in real live.

@howlger may know.

**Comment by howlger** [comment]
> > Does anybody have other ideas how to test? I don't even know where it is used in real live.
> 
> @howlger may know.

I don't know how to test this automatically. The following functions might be affected by the changes:

- [Active help](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/guide/ua_help_content_active.htm), e.g. in _Help > Help Contents: Eclipse Platform User Guide > Getting started > Basic tutorial > The Workbench_ clicking the link "Help > Welcome" should do the same as selecting the menu _Help > Welcome_
- Persistence, e.g. a set search scope (with the link "Scope" to the right of the search field) should still be there after a restart
- Persistence in the [Information Center](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/guide/ua_help_setup_infocenter.htm), e.g. a set search scope should still be there after restarting the web browser

Ideally, this should be tested in different operating systems and with different web browsers.

**Comment by jukzi** [comment]
@howlger i do not understand how to test this before submitting it, as the webpage seems to be hosted on https://help.eclipse.org/

**Comment by howlger** [comment]
> @howlger i do not understand how to test this before submitting it, as the webpage seems to be hosted on https://help.eclipse.org/

The so-called _Information Center_ can be run as a plain, stand-alone Java application as described in the section [_How to start or stop information center from command line_](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/guide/ua_help_setup_infocenter.htm):
```
java -classpath d:\myApp\eclipse\plugins\org.eclipse.help.base_[version].jar org.eclipse.help.standalone.Infocenter -command start -eclipsehome d:\myApp\eclipse -port 8081
```
This will run the  webpage locally at [`http://127.0.0.1:8081/help/index.jsp`](http://127.0.0.1:8081/help/index.jsp) (similar to https://help.eclipse.org/ but with less content).

**Comment by jukzi** [comment]
I restarted both Infocenter  and the webbrowser. After restart the scope is still the configured one: 
image
so it seems to work. - even tough http://127.0.0.1:8081/help/index.jsp is not https.

**Comment by howlger** [comment]
Thanks for testing.

+1 for merging assuming [active help](https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/guide/ua_help_content_active.htm) also still works. It would be great to have this security improvement in M1.

**Pull request merged**
