### PR TITLE
Add public isAnsiConsoleEnabled API

### PR DESCRIPTION
**Pull request by mihnita**
Addressing "[ansiconsole] provide API to check if ANSI is enabled #760" issue

### CODE REVIEW

**Review by laeubi — APPROVED** [review]
Looks good

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
NO new API after M3 please.

**Comment by mihnita** [comment]
Darn, that was close :-)
For me Friday didn't even start.

The change is tiny, but it is your call.

**Comment by erik-brangs** [comment]
It seems this PR was held back because of the API freeze for 2023-12 M3. Can it be merged for 2024-03?

**Comment by merks** [comment]
I just used the rebase button to update the branch.  I expect the `@since` is wrong because a version increment will be needed for the added API.  So more work needs to be done here.

**Comment by mihnita** [comment]
Updated versions.

---

The test failures seem unrelated to this change.

Several caused by
```
Error: Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.internal.JGitText
	... 2 more
```

And several by `NullPointerException` instead of (the expected) `IllegalArgumentException` in `org.eclipse.core.tests.internal.preferences.PreferencesServiceTest.testLookupOrder`

**Comment by mihnita** [comment]
@iloveeclipse Gentle ping

**Comment by mihnita** [comment]
@iloveeclipse, @merks, @erik-brangs, @laeubi  Gentle ping :-)
Thanks!

**Comment by merks** [comment]
I'll assume later today that no one has objections if none are expressed before then.

**Pull request merged**
