### PR TITLE
Remove blank Javadoc

### PR DESCRIPTION
**Pull request by jukzi**
This commit cleans up Javadoc that does not add information. 
It resolves ecj warnings:
 `Javadoc: Description expected after ...`
It helps to prevent future empty javadoc by disabling 
missingJavaDoc warnings. This resolves
 `Javadoc: Missing ...`

The modification is a result of regular expression search&replace:

in files `*.java`
 `^[\s]*\*[\s]*(@return|@param[\s]*[^\s]+|@throws[\s]*[^\s]+)\R([\s]*\*[\s]*@|[\s]*\*/\R)`
 ->`$2`
 `^([\s]*\*[\s]*\R)([\s]*\*/\R)`
 ->`$2`
 `^[\S\t]*/\*\*\R[\s]*\*/\R`
 ->``

in files `org.eclipse.jdt.core.prefs`
 `org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc(Comments|Tags)\=[^\s]*`
 ->`org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc$1\=ignore`

### CODE REVIEW

**Comment by jukzi** [comment]
I need help: the jenkins build keeps failing with wrong API errors:
```
07:53:13.352 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.4-SNAPSHOT:verify (verify) on project org.eclipse.core.runtime: There are API errors:
07:53:13.352 [ERROR] src/org/eclipse/core/runtime/ILog.java:31 The type org.eclipse.core.runtime.ILog has been removed from org.eclipse.core.runtime_3.30.0
...

```

**Comment by iloveeclipse** [comment]
See also https://github.com/eclipse-platform/eclipse.platform.ui/pull/1286 results.
We have a major issue with API tooling in Tycho.

**Comment by jukzi** [comment]
Note this change is supposed to eleminate warings like this:
image

**Review by HeikoKlare — APPROVED** [review]
Great to see this kind of cleanup! I have not checked every single change, but the used patterns look sound and when scanning through some of the changed files I did not find any unexpected changes.

And as a "side effect", although I know this is quite some work for you, @jukzi, it is great to have this PR with many required version bumps at the beginning of the current development cycle. That will ease all further PRs because in most cases no version bumps will be required anymore. So thank you for that!

**Comment by HeikoKlare** [comment]
Remaining test fail is unrelated random fail: #770

**Pull request merged**
