### PR TITLE
Improve JobEventTest.testDeadlockRecovery, avoid random failure (#373)

### LINKED ISSUE #373: Random failing org.eclipse.core.tests.runtime.jobs.JobEventTest.testDeadlockRecovery
```
timeout (probably deadlock)
```

e.g. in 
https://github.com/eclipse-platform/eclipse.platform/pull/371/checks?check_run_id=12255479559
https://github.com/eclipse-platform/eclipse.platform/pull/349/checks?check_run_id=12120746113

Does not occur when locally executing Maven build on Windows and Linux system.

### PR DESCRIPTION
**Pull request by HeikoKlare**
The `testDeadlockRecovery` randomly failed because the deadlock recovery mechanism in `JobListeners.waitAndSendEvents` was still processing the recovery in terms of providing a log entry while the test already failed due to timeout.

Since there is no mechanism to listen to deadlock recovery being finished (and potentially should not be as it may easily lead to a deadlock again), this change increases the timeout (which is not a problem as a timeout is exceptional behavior anyway) and restructures the test to easy comprehension.

The reason for the test failing due to still processing deadlock recovery while running into the test timeout can be seen in the log of this run: https://github.com/eclipse-platform/eclipse.platform/pull/391/checks?check_run_id=12409259744

Fixes #373.

### CODE REVIEW

**Comment by jukzi** [comment]
increasing timeout is a good way to resolve random fails on slow servers

**Comment by HeikoKlare** [comment]
Failures in `IJobManagerTest` in Windows and MacOS build also occur in current CI build of `master` branch, e.g.: https://github.com/eclipse-platform/eclipse.platform/actions/runs/4573426969/jobs/8073852961

**Review by jukzi — APPROVED** [review]
LGTM. but please next time reduce refactoring to a minimum to make review easier.

**Comment by HeikoKlare** [comment]
Thanks, @jukzi, and sorry for the effort! I will reduce refactoring in future pull requests. Could you merge this one?

**Pull request merged**
