### PR TITLE
keep significant white spaces in multiline string literals

### PR DESCRIPTION
**Pull request by tobiasmelcher**
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/584 introduced the functionality to show significant white spaces in string literals in the java compare view when the action "Ignore White Space" is triggered. Unfortunately, this change has a bug and does not work correctly for multiline string literals. Empty lines in multiline string literals are not detected as significant change. 
You can see the behavior in following screenshot:
ignore_whitespace_multiline_string_before
The white space at the end of line 5 is shown correctly as diff when "Ignore White Space" is enabled. The empty line diff in line 8 is not detected.
This pull request will fix this issue and the compare view then looks like this:

ignore_whitespace_multiline_string_after

Could you please review and merge this change?

Thanks a lot and best regards,
Tobias

### CODE REVIEW

**Review by BeckerWdf — APPROVED** [review]

**Comment by BeckerWdf** [comment]
@merks: Is it correct that the freeze-period check says that it's a freeze day?

**Comment by BeckerWdf** [comment]
> @merks: Is it correct that the freeze-period check says that it's a freeze day?

I just re-triggered the check and it's green today.

**Comment by BeckerWdf** [comment]
failed test testLookupOrder (org.eclipse.core.tests.internal.preferences.PreferencesServiceTest is not related to this change. See: https://github.com/eclipse-platform/eclipse.platform/issues/1073

**Comment by BeckerWdf** [comment]
@tobiasmelcher Thanks a lot for keeping up your dedication to improve your initial contributions.

**Comment by merks** [comment]
@BeckerWdf  FYI, there are no freezes until RC1.

**Comment by BeckerWdf** [comment]
> @BeckerWdf FYI, there are no freezes until RC1.

I also had that in mind. But then there's an error in the freeze check. It reported the day of the opening of this PR as a freeze day.

**Comment by akurtakov** [comment]
Calendar wasn't updated . Should be fine now. Sorry for that!

**Pull request merged**
