### PR TITLE
Add generics to new org.eclipse.core.resource.undo.snapshots

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by mickaelistria** [comment]
@robstryker Can you please review this? I try to add stronger typing so clients should deal less with cast and potential ClassCastException

**Comment by robstryker** [comment]
Investigating. Thanks for the PR.

**Comment by robstryker** [comment]
I'm fine with a +1 on this. If you think this is better design I'm inclined to agree that updating the code to use more modern features is to our benefit.

**Comment by mickaelistria** [comment]
Thanks. Would it be OK to merge now?

**Comment by robstryker** [comment]
should be fine

**Pull request merged**
