### PR TITLE
Remove the ant infrastructure to pre-compile JSPs in the IDE

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform/issues/612

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse @akurtakov 

There seems to be a sea of failures here, but nothing actually related to my PR, which, as far as I know, has zero impact on the Tycho build.  Are we currently in a really bad state for some reason?  (Even trying to read a log for "Verify Linux" finds all kinds of output from running tests interspersed in the log for build org.eclipse.help.webapp.)   And for "continuous-integration/jenkins/pr-head" it doesn't even try to build:
```
09:25:12.309 [INFO] Skipping org.eclipse.help.webapp
09:25:12.310 [INFO] This project has been banned from the build due to previous failures.
```

**Comment by laeubi** [comment]
@merks the API tools execution currently fails on Jenkins:

> Failed to execute goal org.eclipse.tycho:tycho-apitools-plugin:4.0.2:verify (verify) on project org.eclipse.debug.core: Execute ApiApplication failed: Application returned exit code 10 -> [Help 1]

While on GH actions there is for Linux e.g. a test failure:

> org.eclipse.ua.tests.doc: There are test failures

**Comment by merks** [comment]
Still failures but none related to my changes.  I am tempted to "just Squash and merge" this...

**Comment by akurtakov** [comment]
Keeping clean build has been always hard .

**Pull request merged**
