### PR TITLE
Test improvements

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by jukzi** [comment]
@akurtakov the commit "Remove useless assert/fail methods from CoreTest" broke a lot of tests on windows. 
(see https://github.com/eclipse-platform/eclipse.platform/issues/265)
reproducible locally for example: org.eclipse.core.tests.resources.LinkedResourceTest.testBlockedFolder()
`org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
`
please fix or revert

**Comment by jukzi** [comment]
Please note that the removed CoreTest.assertClose() did not only asserted but was used to close the files

**Comment by akurtakov** [comment]
All assertClose should be in try-with-resources with this change so supposedly not an issue unless I've missed some. I'm looking into it.

**Comment by jukzi** [comment]
The org.eclipse.core.resources.IFile.getContents() then also needs to be used as try-with-resources

**Comment by akurtakov** [comment]
I have opened https://github.com/eclipse-platform/eclipse.platform/pull/274 with the initial issue you pointed to to see windows failures proper and will build on top of that to get them fixed. Now that there is verification job showing the issue things should be easier.

**Pull request merged**
