### PR TITLE
Remove unused require bundle (that was even marked optional)

### PR DESCRIPTION
**Pull request by laeubi**
Seems not used anyways...

### CODE REVIEW

**Comment by laeubi** [comment]
From the history, this was added to use DS annotations ...

**Comment by laeubi** [comment]
@akurtakov can this be merged or is there any freeze period? But I think this can also wait so I'll leave this up to you :-)

**Review by akurtakov — APPROVED** [review]
I'm fine with merging this one for RC1

**Comment by akurtakov** [comment]
In a way it's releng improvement :) .

**Pull request merged**
