### PR TITLE
Remove activate="activate"

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform/issues/1003

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse 

Please merge this when it's ready.

**Comment by iloveeclipse** [comment]
> Please merge this when it's ready.

If that is what expected to be in the source tree, I will do that. However I have no clue about this code.

**Comment by merks** [comment]
Either they should be committed in the current generated state or not committed at all. But the latter can be done later.

I'm not sure what to make of the failures.  😱

**Comment by iloveeclipse** [comment]
> I'm not sure what to make of the failures.

You are not alone. That's the "quality gate", see https://github.com/eclipse-platform/eclipse.platform/issues/969

**Comment by iloveeclipse** [comment]
Tests are fine: https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-1006/1/testReport/
image

**Pull request merged**
