### PR TITLE
Merge eclipse.platform.ua into the platform repo

### PR DESCRIPTION
**Pull request by vogella**
Tested with `mvn clean verify -Dtycho.resolver.classic=true  -DskipTests=true -Pbuild-individual-bundles`

To make it successfully I had to remove the target configuration in org.eclipse.ua.tests.doc

````
 <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>target-platform-configuration</artifactId>
        <configuration>
          <dependency-resolution>
	          <extraRequirements>
	            <requirement>
	              <type>eclipse-feature</type>
	              <id>org.eclipse.jdt</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-feature</type>
	              <id>org.eclipse.pde</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-feature</type>
	              <id>org.eclipse.equinox.core.feature</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-feature</type>
	              <id>org.eclipse.equinox.server.jetty</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.ui.cheatsheets</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.help.ui</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.ui.monitoring</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.unittest.ui</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.ui.browser</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.ui.intro.quicklinks</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.ui.intro.universal</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.jsch.ui</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	             <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.core.databinding.beans</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.jdt.doc.isv</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.jdt.doc.user</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.pde.doc.user</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.platform.doc.isv</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	            <requirement>
	              <type>eclipse-plugin</type>
	              <id>org.eclipse.platform.doc.user</id>
	              <versionRange>0.0.0</versionRange>
	            </requirement>
	          </extraRequirements>
	      </dependency-resolution>
        </configuration>
      </plugin>

````

### CODE REVIEW

**Comment by laeubi** [comment]
> To make it successfully I had to remove the target configuration in org.eclipse.ua.tests.doc

You should add the bundles that are mentioned there in a "additional.bundles" section in the build properties (we might no longer need all but simply c&p all would be the easiest) like this:

https://github.com/eclipse-platform/eclipse.platform/blob/127f06ff1714e2f20125fb77a8ee59706eb8c1c4/runtime/tests/org.eclipse.core.expressions.tests/build.properties#L29

**Comment by merks** [comment]
The build fails with this error:

> 10:40:06.837 [ERROR]   Missing requirement: org.eclipse.jdt.feature.group 3.19.0.v20230205-1800 requires 'org.eclipse.equinox.p2.iu; org.eclipse.ant.ui [3.8.300.v20220718-1722,3.8.300.v20220718-1722]' but it could not be found

But that exact version is available in  https://download.eclipse.org/eclipse/updates/4.27-I-builds

image

There is no recent activity in that plugin:

image

This looks like a "new resolver" type of problem...

**Comment by laeubi** [comment]
I have resceduled the Jenkins build now.

**Comment by vogella** [comment]
I see tons of warnings like the following:

````
15:59:45.860 [WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).]

`````

And still the error which @merks already said should not happen:

````
15:59:47.938 [ERROR]   Software being installed: org.eclipse.jdt.feature.group 3.19.0.v20230208-0150
15:59:47.938 [ERROR]   Missing requirement: org.eclipse.jdt.feature.group 3.19.0.v20230207-1800 requires 'org.eclipse.equinox.p2.iu; org.eclipse.ant.ui [3.8.300.v20220718-1722,3.8.300.v20220718-1722]' but it could not be found
15:59:47.938 [ERROR]   Missing requirement: org.eclipse.jdt.feature.group 3.19.0.v20230208-0150 requires 'org.eclipse.equinox.p2.iu; org.eclipse.ant.ui [3.8.300.v20220718-1722,3.8.300.v20220718-1722]' but it could not be found
15:59:47.938 [ERROR] 
`````

So I assume we see an error from Tycho. org.eclipse.ant.ui is there as @merks said

cc @akurtakov and @laeubi

**Comment by laeubi** [comment]
You can ignore the warnings, but as said before some version bumps (or something else) is missing because (a bit reformatted by me):

Missing requirement: 
```
org.eclipse.jdt.feature.group 3.19.0.v20230207-1800
org.eclipse.jdt.feature.group 3.19.0.v20230208-0150
```

seem to pull in the same thing with different qualifiers what will not play very well.

**Comment by laeubi** [comment]
@vogella I have take a look now and running for example with option `-fae` shows some projects that need version bump, also the pom `ua/tests-pom` references old platform.ua parent pom. I'll try to submit a patch you can merge into your branch then.

**Comment by laeubi** [comment]
Also there are some pom.xml files that still reference old ua parent....

**Comment by laeubi** [comment]
I now was able to build all except `org.eclipse.ua.tests.doc`. The resolution fails, because it explicitly requesting jdt + pde features and as these refer to fixed build version of `org.eclipse.ant.ui` but this is part of the reactor the reactor version overrides the one from the i-builds. One solution would be for `org.eclipse.jdt.feature` to not include `org.eclipse.ant.ui` (if it is required it will be transitively installed anyways), I'll try if the test probably just don't need to reference the feature.

**Comment by laeubi** [comment]
I created
- https://github.com/eclipse-platform/eclipse.platform.ua/pull/97

to investigate on this...

**Comment by laeubi** [comment]
By the way that exactly is showing the problem currently hidden by the "useful behavior" of Tycho platform currently depends on we have [discussed recently here](https://github.com/eclipse-platform/eclipse.platform/pull/328) because there is a cyclic build dependency between platform.ua -> pde ->  jdt -> platform and jdt depend on platform ...

**Comment by laeubi** [comment]
@vogella I have pushed the missing version bumps here:
https://github.com/laeubi/eclipse.platform/tree/pr-330-merge-repo-ua

**Comment by laeubi** [comment]
I now added support for discovering such "shadowed" units in a resolve operation to Tycho:
- https://github.com/eclipse-tycho/tycho/pull/2092

once this is merged, it should allow to resolve this situation and make the merge possible.

**Comment by laeubi** [comment]
@vogella the build now fails with the (expsected) missing qualifier changes, so you can either apply them yourself or cherry pick them from my branch (it seems there are also some changes on master to be merged).

**Comment by vogella** [comment]
Thanks @laeubi for all your work, I applied your version increase onto the branch. Lets see what the CI thinks now.

**Comment by vogella** [comment]
A new build error:

09:05:35.128 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (default) on project infocenter-app: An Ant BuildException has occured: /home/jenkins/agent/workspace/eclipse.platform_PR-330/ua/infocenter-web/infocenter-product/target/products/infocenter/linux/gtk/x86_64/infocenter does not exist.
09:05:35.129 [ERROR] around Ant part ...<copy todir="src/main/webapp/WEB-INF">... @ 4:43 in /home/jenkins/agent/workspace/eclipse.platform_PR-330/ua/infocenter-web/infocenter-app/target/antrun/build-main.xml
09:05:35.129 [ERROR] -> [Help 1]

In my local build this folder exists. And as the path name is relativ in pom.xml I do not see why the move should break it. Someone knows that is wrong here?

Relevant pom file from infocenter-web/infocenter-app/pom.xml:

````
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) 2020 Eclipse Foundation. All rights reserved. This program 
	and the accompanying materials are made available under the terms of the 
	Eclipse Distribution License v1.0 which accompanies this distribution, and 
	is available at http://www.eclipse.org/org/documents/edl-v10.php Contributors: 
	Karsten Thoms - initial implementation -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.eclipse.help</groupId>
		<artifactId>infocenter-parent</artifactId>
		<version>4.27.0-SNAPSHOT</version>
	</parent>
	<artifactId>infocenter-app</artifactId>
	<packaging>war</packaging>
	<build>
		<finalName>help</finalName>
		<plugins>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<configuration>
					<filesets>
						<fileset>
							<directory>src/main/webapp/WEB-INF</directory>
							<includes>
								<include>configuration/**</include>
								<include>lib/**</include>
								<include>plugins/**</include>
								<include>*.ini</include>
							</includes>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<?m2e ignore?>
						<phase>process-resources</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<copy todir="src/main/webapp/WEB-INF">
									<fileset
										dir="../infocenter-product/target/products/infocenter/linux/gtk/x86_64/infocenter"
										includes="**" excludes="artifacts.xml,p2/**"/>
								</copy>
								<copy todir="src/main/webapp/WEB-INF/lib">
									<fileset dir="src/main/webapp/WEB-INF/plugins"
										includes="*.equinox.servletbridge_*.jar" />
								</copy>
								<!-- org.eclipse.equinox.servletbridge.FrameworkLauncher.LAUNCH_INI -->
								<move file="src/main/webapp/WEB-INF/eclipse.ini" tofile="src/main/webapp/WEB-INF/launch.ini"/>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

````

**Comment by laeubi** [comment]
Probably an ordering issue (where is the missing stuff generated?) but I never got this ant build stuff working on my local machine to tell more so this is just an idea, e.g. if the step that produces this is running too late or has failures ..

But I'm a bit curious why we need ant here at all should this not be done by [Maven Resources Plugin](https://maven.apache.org/plugins/maven-resources-plugin/)?

**Comment by laeubi** [comment]
@akurtakov can you take a look why this script complains? I assume something might happen "to early" now maybe? If we know whats specifically is missing here I might can propose a fix.

> In my local build this folder exists. 

Have you tried to clear all generated folders before the build? It might be created later on, also sometimes `-Dtycho.localArtifacts=ignore` is a good choice and the build should best run with `-T1C` to account for any concurrency that might affect the parts. maybe an explicit requirement in the pom is needed here to make sure the prerequisite is always build first?

**Comment by akurtakov** [comment]
I'll take a look.

**Comment by vogella** [comment]
> @vogella maybe it would be good to start this from a fresh master? Or maybe first go ahead with merging other repos if the `platform.ua` is to complicated?

Sure, which other repo should we merge to what target? My personal target is to have at least one repo less per release.

**Comment by laeubi** [comment]
Maybe platform.text? I'm not sure what was the decision here @mickaelistria / @akurtakov I was sure we have had discussed this but I can't find the issue / discussion atm...

**Comment by laeubi** [comment]
Maybe also 
https://github.com/eclipse-platform/eclipse.platform.debug

**Comment by akurtakov** [comment]
platform.text is the only repo building on CentOS 7 as there are test failures when run on CentOS8 . See https://github.com/eclipse-platform/eclipse.platform.text/pull/162 . Either the test will have to be disabled or fixed before it can be updated and/or merged into another repo . Unfortunately, I don't think I would have time to look into that soon.

**Comment by vogella** [comment]
I think the CentOS stuff has been sorted out? Could be continue here? I so far failed with my personal target to reduce the number of repos by at least one per release.

**Comment by laeubi** [comment]
You probably want to restart the merge from fresh then as both repos have diverged a bit in the meanwhile, personally I don't see issue in proceeding ...

**Comment by HeikoKlare** [comment]
@vogella I guess this PR can be closed since it was superseded by #555?

**Comment by akurtakov** [comment]
This has been completed months ago.

**Pull request closed without merging**
