### PR TITLE
BuildManager: compute delta only for relevant projects #111

### PR DESCRIPTION
**Pull request by jukzi**
Previously the delta for the whole workspace was calculated even though
it was only checked for few projects. That caused a large overhead for
Workspaces with a lot projects.

### CODE REVIEW

**Comment by jukzi** [comment]
@jhonnen 
The computed delta of the whole workspace was never relay used - only for the relevant projects.
What's the (big) difference between DeltaDataTree.compareWith and DeltaDataTree.forwardDeltaWith? is it relevant?
I did not test this at all yet - just to get a idea and a CI test result

**Comment by jhonnen** [comment]
> What's the (big) difference between DeltaDataTree.compareWith and DeltaDataTree.forwardDeltaWith? is it relevant?

It probably has something to do with that part

```
	 * There is no requirement that a and b be related, although it is usually more
	 * efficient if they are. The node keys are used as the basis of correlation
	 * between trees.
	 *
	 * Note that if b is already represented as a delta over a,
	 * then c will have the same internal structure as b.
	 * Thus the very common case of previous forwardDeltaWith: current
	 * is actually very fast when current is a modification of previous.
```
... but I don't know what that means exactly, I'm not familiar with the delta computation.

**Comment by jukzi** [comment]
unrelated OrderedLockTest.testLockRequestDisappearence failed

**Comment by jukzi** [comment]
The current "solution" is sometimes slower then the previous code.

**Comment by jukzi** [comment]
There is something wrong in DeltaDataTree.basicCompare: the basicCompare loops over all tree.parent and calls searchNodeAt which also loops over the same trees. As the trees grows this is an O(n^2) for n trees:
image
The outer loop should continue at the tree where the inner loop found a result to avoid handling the same node over and over.

**Comment by jukzi** [comment]
... or the inner loop should not loop over the trees too :-)

**Comment by jukzi** [comment]
Performance for my workspace with ~500 projects:
Each needsBuild() did cost about  ~00ms which is reduced to ~1ms.
The total full autobuild (upon changing the manifest) is reduced from 550sec to 420sec.
before:
image
after:
image

It has a slight overhead if there is no delta, but that is irrelevant as both implementations are extremely quick (<1ms) when there is no delta.

In total it is a significant performance gain for autobuild with many projects in workspace after https://github.com/eclipse-platform/eclipse.platform/pull/186 was fixed

**Comment by iloveeclipse** [comment]
Please check https://github.com/eclipse-platform/eclipse.platform/issues/243 for a possible regression.

**Pull request merged**
