### PR TITLE
Migrating faq wiki to markdown

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by jukzi** [comment]
@vogella 
Lars, this causes serious issues on windows, as the file name contains a ",", which is not alllowed on windows
https://github.com/eclipse-platform/eclipse.platform/blob/master/docs/FAQ/FAQ_Actions%2C_commands%2C_operations%2C_jobs%3A_What_does_it_all_mean.md

i can not pull anymore!

```
An internal error occurred during: "Pulling origin from https://github.com/eclipse-platform/eclipse.platform.git".
Invalid path: docs/FAQ/FAQ_Actions,_commands,_operations,_jobs:_What_does_it_all_mean.md
```

**Comment by jukzi** [comment]
BTW the Windows build shows the same error, so you can verify that all files fixed without having windows:
image

**Comment by vogella** [comment]
Thanks for the tip

**Comment by vogella** [comment]
Windows Git pull should be fixed with https://github.com/eclipse-platform/eclipse.platform/pull/1201, this will break a few links which will be corrected in a separate PR.
@jukzi please trying pulling and let @jnerlich and me know if this is fixed for you.

**Comment by vogella** [comment]
Fresh clone worked for me in Windows. Pulling for an existing clone also worked. So hopefully this is also solved for you @jukzi

**Comment by jukzi** [comment]
yes, thanks.

**Pull request merged**
