### PR TITLE
Revert 1220

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-platform/eclipse.platform/pull/1246#issuecomment-1993788432

### CODE REVIEW

**Review by jukzi — CHANGES_REQUESTED** [review]
-1 because just back&forth does not help. If you have valid regressions with the changes to reverted then please report those first as usual.

**Comment by iloveeclipse** [comment]
> -1 because just back&forth does not help. If you have valid regressions with the changes to reverted then please report those first as usual.

Jörg, this time I'm not acting as a committer, but as a project lead.
I hope you read my explanation for this PR, please accept that.

**Comment by jukzi** [comment]
> Jörg, this time I'm not acting as a committer, but as a project lead.

A revert will not solve social interaction. Also i doubt you are acting unbiased here as nobody else requested a revert.

**Comment by akurtakov** [comment]
> > Jörg, this time I'm not acting as a committer, but as a project lead.
> 
> A revert will not solve social interaction. Also i doubt you are acting unbiased here as nobody else requested a revert.

If you disagree with Project lead decision here are the rules  - https://github.com/eclipse-platform/.github/wiki/PMC-project-guidelines#committer-disagreement-resolution .

**Comment by akurtakov** [comment]
FWIW, merging patches that there has been disagreement on is a no-go.

**Pull request merged**
