### PR TITLE
Merge ua

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/eclipse-platform/eclipse.platform.ua/issues/163

### CODE REVIEW

**Comment by akurtakov** [comment]
Could someone verify git history status?

**Review by merks — APPROVED** [review]
I don't know how to review something this big, but I trust @laeubi 's experience with this process.  I hope that @iloveeclipse can confirm that the history is intact.  I don't know how he does that!

**Comment by merks** [comment]
FYI, I have the setup changes mostly ready locally so I can update and commit it quite quickly once I see the changes merged...

**Comment by akurtakov** [comment]
I don't understand why the jenkins build failed.

**Comment by laeubi** [comment]
I think this is because we have warnings as errors and there is:

```
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[31] 
	import org.eclipse.core.internal.net.ProxyManager;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Discouraged access: The type 'ProxyManager' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[54] 
	IProxyService service = ProxyManager.getProxyManager();
	                        ^^^^^^^^^^^^
Discouraged access: The type 'ProxyManager' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[54] 
	IProxyService service = ProxyManager.getProxyManager();
	                                     ^^^^^^^^^^^^^^^
Discouraged access: The method 'ProxyManager.getProxyManager()' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[96] 
	IProxyService service = ProxyManager.getProxyManager();
	                        ^^^^^^^^^^^^
Discouraged access: The type 'ProxyManager' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[96] 
	IProxyService service = ProxyManager.getProxyManager();
	                                     ^^^^^^^^^^^^^^^
Discouraged access: The method 'ProxyManager.getProxyManager()' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[99] 
	if (service instanceof ProxyManager)
	                       ^^^^^^^^^^^^
Discouraged access: The type 'ProxyManager' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[100] 
	natives = ((ProxyManager)service).getNativeNonProxiedHosts();
	            ^^^^^^^^^^^^
Discouraged access: The type 'ProxyManager' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
14:32:24.946 [WARNING] /home/jenkins/agent/workspace/eclipse.platform_PR-555/ua/org.eclipse.help.base/src/org/eclipse/help/internal/base/util/ProxyUtil.java:[100] 
	natives = ((ProxyManager)service).getNativeNonProxiedHosts();
	                                  ^^^^^^^^^^^^^^^^^^^^^^^^
Discouraged access: The method 'ProxyManager.getNativeNonProxiedHosts()' is not API (restriction on classpath entry '/home/jenkins/agent/workspace/eclipse.platform_PR-555/team/bundles/org.eclipse.core.net/target/classes')
```

**Comment by laeubi** [comment]
I tried to include a fix for that...

**Comment by iloveeclipse** [comment]
> I hope that @iloveeclipse can confirm that the history is intact. I don't know how he does that!

So that is basically some smoke test about being able to see files history after merge - they shouldn't appear for the "first time ever" in the history after merge.

1) fetch PR into Eclipse
2) remove existing projects from old repo
3) import all project from "common" repo
4) check the history view of the "common" repo 
4.1) last commit before merge should be the last commit of the old repo
4.2) the "old" files shouldn't be "added" in merge
5) open some older file and show git history for that file only - it should show all revisions down to 200X year.
6) git blame in editor should be able to show more than one revision for that file

Regarding this PR: git history looks OK for me. I haven't checked anything else.

**Comment by laeubi** [comment]
Jenkins is fine now.

**Pull request merged**
