### PR TITLE
fix some JavaDoc

### PR DESCRIPTION
**Pull request by jukzi**
mostly "@param name not found", "reference not found"

### CODE REVIEW

**Comment by Bananeweizen** [comment]
Please don't replace inline `{@code foo}` by XML `<code>foo</code>`. They are not the same. The inline tag supports special characters without escaping and is therefore easier to write. Only for multi-line code the XML version should be used, since it preserves line breaks.

**Comment by jukzi** [comment]
> Please don't replace inline `{@code foo}` by XML `<code>foo</code>`. They are not the same. The inline tag supports special characters without escaping and is therefore easier to write. Only for multi-line code the XML version should be used, since it preserves line breaks.

`{@code true}` does not contain any special character. the build does report it as wrong. how to solve?

**Comment by Bananeweizen** [comment]
> `{@code true}` does not contain any special character. the build does report it as wrong. how to solve?

Not sure what build you refer to, can you share a link? `{@code true}` is surely valid Javadoc. The curly brace version only exists since Java 5, so a misconfiguration of the compliance level within the checker could potentially raise an error here (but I think chances for that are low).

**Comment by jukzi** [comment]
https://ci.eclipse.org/platform/job/eclipse.platform/job/master/415/consoleText

**Comment by jukzi** [comment]
my bad, the error complains about AssertionFailedError in the same lines

**Review by Bananeweizen — APPROVED** [review]

**Review by akurtakov — APPROVED** [review]

**Pull request merged**
