### PR TITLE
Revert "Use org.eclipse.platform as groupId"

### PR DESCRIPTION
**Pull request by jukzi**
Reverts eclipse-platform/eclipse.platform#166

JSCH test failures

### CODE REVIEW

**Comment by jukzi** [comment]
let's test if a revert would make CI work again

**Comment by mickaelistria** [comment]
OK, I now see the cause of the error and it's indeed the patch causing it. I didn't notice it in previous build as it was reporting another test failure as well.
Please don't merge the revert, I'll submit a more focused fix (basically replacing the pom.xml that was removed for this bundle so it's not detected as a test).

**Comment by mickaelistria** [comment]
#174 is supposed to fix it.

**Comment by mickaelistria** [comment]
Thanks for the heads-up. This is now fixed with #174

**Pull request closed without merging**
